name: Linting
on: [push]

jobs:
  prose:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Get Changed Files
      id: get_changed_files
      uses: lots0logs/gh-action-get-changed-files@2.1.4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Vale
      uses: errata-ai/vale-action@v2.0.1
      with:
        files: '${{ steps.get_changed_files.outputs.all }}'
      env:
        # Required
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
